package com.rakovpublic.jneuropallium.worker.demo.uavsingle;

public enum UavMissionState {
    INITIALIZING,
    PREFLIGHT_CHECK,
    TAKEOFF_REQUESTED,
    SEARCHING,
    TARGET_CANDIDATE_FOUND,
    TARGET_EVALUATION,
    TARGET_SELECTED,
    APPROACHING_SAFE_OBSERVATION_POINT,
    HOLDING_FOR_CONFIRMATION,
    CONFIRMED,
    DENIED,
    CONFIRMATION_TIMEOUT,
    OBSERVING,
    PHOTOGRAPHING,
    VERIFYING_PHOTO,
    SAFETY_HOLD,
    RETURNING_HOME,
    ABORTED,
    LANDED,
    COMPLETED
}

