- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
- ros_topic_name: /uav_1/fpv/image
  gz_topic_name: /world/jneo/model/uav_1/link/base_link/sensor/fpv_camera/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: /uav_1/fpv/camera_info
  gz_topic_name: /world/jneo/model/uav_1/link/base_link/sensor/fpv_camera/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: /uav_1/imu
  gz_topic_name: /world/jneo/model/uav_1/link/base_link/sensor/imu/imu
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS
- ros_topic_name: /uav_1/range
  gz_topic_name: /world/jneo/model/uav_1/link/base_link/sensor/range/scan
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS
- ros_topic_name: /uav_1/odometry
  gz_topic_name: /model/uav_1/odometry
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS
# Hidden evaluator topics are intentionally absent from this file.

